# Site settings
title: Portfolio for main(String[] args)
description: Portfolio for main(String[] args)
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: main(String[] args)
user_description: A Software Developer that loves a good challenge.
user_title: Software Developer
email: anon@anon.com
#twitter_username: lorem_ipsum
github_username:  mainstringargs
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-1749812-7"

exclude: ['package.json', 'src' , 'node_modules']
